name: Flutter CI

on:
  push:
    branches:
      - main
      - Translator
      - NLP-model
      - System_Front-Back-end
  pull_request:
    branches:
      - main     

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.2'  # Set the desired Flutter version
          channel: 'stable'
      - run: flutter build apk

      - name: Install dependencies
        run: flutter pub get

      - name: Build for Android
        run: flutter build apk

      - name: Build for iOS
        run: flutter build ios --no-codesign

      - name: Run tests
        run: flutter test
