name: Flutter CI

on:
  push:
    branches:
      - main
      - Translator
      - NLP-model
      - System_Front-Back-end
  pull_request:
    branches:
      - main     

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Install Flutter
       uses: subosito/flutter-action@v2
       with:
          flutter-version: '2.10.0'
          channel: 'stable'

     - name: Install dependencies
       run: flutter pub get
